---
title: "Research"
author: "Richard Lussier"
date: "12/9/2021"
output: html_document
params:
    data_file: "XOResultsMC"
    orignal_step_limit: 200
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library('ggplot2')
library('dplyr')
library('ggpubr')
library('gridExtra')
library('ggforce')
library('ggpmisc')
```


```{r}
researchData = read.table("MiddleCharData.txt", header=T, sep="\t")

researchData$NumFailedCases <- as.numeric(researchData$NumFailedCases)
researchData$TotalError <- as.numeric(researchData$TotalError)
researchData$StepLimit <- as.numeric(researchData$StepLimit)
researchData$FailedByStepLimit <- as.numeric(researchData$FailedByStepLimit)
researchData$RunNumber <- as.numeric(researchData$RunNumber)
researchData$Succeeded. <- as.logical(researchData$Succeeded.)
researchData$Generalized. <- as.logical(researchData$Generalized.)

#plot(x=researchData$StepLimit, y=log(researchData$TotalError)) + geom_point(alpha=0.1)

ggplot(researchData, aes(x=StepLimit, y=NumFailedCases, color=factor(Generalized.))) + geom_point(alpha=0.1)

ggplot(researchData, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber))) + geom_line(alpha=0.1)
```

Let's add a new column that is true if `FailedCases = FailedByStepLimit`:

```{r}
researchData$AllFailuresOutOfSteps = (researchData$NumFailedCases == researchData$FailedByStepLimit)

equalFailures = subset(researchData, researchData$AllFailuresOutOfSteps)

nrow(equalFailures)

ggplot(equalFailures, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```
```{r}
fewFailedCases <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(max(NumFailedCases) < 250)

succeededAt2000 <- researchData %>%
  group_by(RunNumber) %>%
  filter(StepLimit == 2000 & Succeeded. == TRUE)

generalizedAt2000 <- subset(researchData, (researchData$StepLimit == 2000 & researchData$TotalError == 0))$RunNumber

ggplot(fewFailedCases, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=TRUE)
```
```{r}
fourFiveand92 <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(RunNumber == 95 || RunNumber == 37 || RunNumber == 28)

ggplot(fourFiveand92, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```

```{r}
middleFailedCases <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(max(NumFailedCases) >= 750 && max(NumFailedCases) < 1250)

ggplot(middleFailedCases, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```
```{r}
higherFailedCases <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(max(NumFailedCases) >= 1250 && max(NumFailedCases) < 1970)

ggplot(higherFailedCases, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```
```{r}
highestFailedCases <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(max(NumFailedCases) >= 1970 && max(NumFailedCases) < 2001)

ggplot(highestFailedCases, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```

```{r}
reachesZeroFailedCases <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(min(NumFailedCases) == 0)

midCharSucceedSomePoint <- equalFailures %>%
  group_by(RunNumber) %>%
  filter(min(equalFailures$NumFailedCases) == 0)

generalizedNotAt2000 <- subset(reachesZeroFailedCases, (reachesZeroFailedCases$StepLimit == 2000 & reachesZeroFailedCases$TotalError > 0))$RunNumber

#MidGeneralizedSomewhereNot2000 <- subset(MiddleCharData, MiddleCharData$TotalError == 0 & RunNumber Negate(%in%) generalizedAt2000)$RunNumber

GenSomewhereElse <- researchData %>%
  filter(RunNumber %in% generalizedNotAt2000)

ggplot(GenSomewhereElse, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggplot(reachesZeroFailedCases, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```

```{r}
run70 <- subset(equalFailures, equalFailures$RunNumber == 70)

ggplot(run70, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggplot(run70, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE) + coord_cartesian(xlim = c(1950,2020), ylim = c(0,50))
  
  #xlim(1950,2020) + ylim(0,50)
```

```{r}
runsRunningOutAt2200 <- subset(researchData, (researchData$StepLimit == 2200) & (researchData$AllFailuresOutOfSteps) & researchData$TotalError > 0 & as.numeric(researchData$NumFailedCases) < 100)$RunNumber

runningOutAt2200 <- researchData %>%
  filter(RunNumber %in% runsRunningOutAt2200)

ggplot(runningOutAt2200, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```

```{r}
dataset <- read.csv(params$data_file, sep="")

# The new AllFailuresOutOfSteps column is true for any program & step limit where
# that program fails all of its test cases because it runs out of steps. So if
# *any* case completes "normally" that (program, step limit) pair won't be set
# to TRUE here.
dataset$AllFailuresOutOfSteps = (dataset$NumFailedCases == dataset$FailedByStepLimit)

runsRunningOutAt350 <- subset(dataset, dataset$StepLimit == 350 & dataset$AllFailuresOutOfSteps & dataset$TotalError > 0 & dataset$NumFailedCases < 100)$RunNumber

runningOutAt350 <- dataset %>%
  filter(RunNumber %in% runsRunningOutAt350)

ggplot(runningOutAt350, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)
```

```{r}
# All the (program, step limit) pairs where where all failures
# came from running out of steps.
equalFailuresLastIndex = subset(dataset, dataset$AllFailuresOutOfSteps)

# All the programs (i.e., runs) that generalize for at least one
# step limit, i.e., min(FailedCases) == 0, i.e., the min across
# all the possible step limits is 0.
lastIndexOutOfSteps <- equalFailuresLastIndex %>%
  group_by(RunNumber) %>%
  filter(min(NumFailedCases) == 0)

#generalizedAtSomePoint <- subset(lastIndexOutOfSteps, lastIndexOutOfSteps$TotalError == 0)

# All the programs that generalize somewhere *other* than at
# step limit 200.
generalizedNotAt200 <- subset(lastIndexOutOfSteps, 
                              (lastIndexOutOfSteps$StepLimit == params$orignal_step_limit 
                               & lastIndexOutOfSteps$TotalError > 0))$RunNumber

generalizedAt200 <- subset(lastIndexOutOfSteps, (lastIndexOutOfSteps$StepLimit == params$orignal_step_limit & lastIndexOutOfSteps$TotalError == 0))$RunNumber

didntGenAt200 <- dataset %>%
  filter(RunNumber %in% generalizedNotAt200)

generalizedSomewhereNot200 <- subset(didntGenAt200, didntGenAt200$TotalError == 0)$RunNumber

didntGenAt200 <- didntGenAt200 %>%
  filter(RunNumber %in% generalizedSomewhereNot200)

#Would most likely have to clean this up. Maybe limit the amount of runs per graph and have multiple?
ggplot(didntGenAt200, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

```

```{r}
ggplot(didntGenAt200, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE) + xlim(params$orignal_step_limit-10, params$orignal_step_limit+10) + ylim(0, 20)
```

```{r}
someRunNumbersFailingLessThan20 <- head(unique(subset(didntGenAt200, (didntGenAt200$NumFailedCases < 20) & (didntGenAt200$StepLimit == params$orignal_step_limit))$RunNumber), 10)

someRunsFailingLessThan20 <- subset(didntGenAt200, didntGenAt200$RunNumber %in% someRunNumbersFailingLessThan20)

ggplot(someRunsFailingLessThan20, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE) + xlim(params$orignal_step_limit-10, params$orignal_step_limit+10
                                                                                                                                                                         ) + ylim(0, 20)
```

```{r}
`500popMC` <- read.csv("500popMC.txt", sep="")

`500popMC`$AllFailuresOutOfSteps = (`500popMC`$NumFailedCases == `500popMC`$FailedByStepLimit)

equalFailures200Mid = subset(`500popMC`, `500popMC`$AllFailuresOutOfSteps)

Mid200OutOfSteps <- equalFailures200Mid %>%
  group_by(RunNumber) %>%
  filter(min(`500popMC`$NumFailedCases) == 0)

MidGeneralizedNotAt200 <- subset(Mid200OutOfSteps, (Mid200OutOfSteps$StepLimit == 200 & Mid200OutOfSteps$TotalError > 0))$RunNumber

MidGeneralizedAt200 <- subset(Mid200OutOfSteps, (Mid200OutOfSteps$StepLimit == 200 & Mid200OutOfSteps$TotalError == 0))$RunNumber

MidGenAt200 <- `500popMC` %>%
  filter(RunNumber %in% MidGeneralizedAt200)

MidDidntGenAt200 <- `500popMC` %>%
  filter(RunNumber %in% MidGeneralizedNotAt200)

MidGeneralizedSomewhereNot200 <- subset(MidDidntGenAt200, MidDidntGenAt200$TotalError == 0)$RunNumber

GenSomewhere <- `500popMC` %>%
  filter(RunNumber %in% MidGeneralizedSomewhereNot200)

ggplot(`500popMC`, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggplot(MidDidntGenAt200, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggplot(MidGenAt200, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggplot(GenSomewhere,aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)




XOMiddleCharData <- read.csv("XOResultsMC.txt", sep="")

allXORunsMC <- ggplot(XOMiddleCharData, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)

ggexport(allXORunsMC, filename="hd_allXORunsMC.png", width=800, height=800)
```


```{r}

#This function combines all of the helper functions below. It takes the dataset, the step limit the problem was originally run on, and a string, which is the .png file you would like to export the graphs to (for example, "example.png").
GenerateGraphs <- function(givenData, originalStepLimit, saveToFile, groupPlots=TRUE) {
  
  givenData <- WrangleData(givenData)
  
  #Store the graphs into variables
  graph1 <- GraphOriginalGeneralizations(givenData, originalStepLimit)
  graph2 <- GraphOtherGeneralizations(givenData, originalStepLimit)
  graph3 <- GraphRunningOutOfSteps(givenData)
  
  #Put every graph into a list
  graphList <- list(graph1, graph2, graph3)
  
  #Print all graphs on one file if true, in separate files otherwise.
  if(groupPlots){
    allGraphs <- ggarrange(plotlist=graphList, ncol = 1, nrow = 3)
  
    ggexport(allGraphs, filename=saveToFile)
  } else {
    for(i in 1:length(graphList)){
      
      fileName <- paste(i, saveToFile, sep="_")
      ggexport(graphList[i], filename=fileName, width=800, height=800)
    }
  }
  
  
}




#This function takes a dataset with specific column names (RunNumber, Succeeded., Generalized., StepLimit, TotalError, NumFailedCases, and FailedByStepLimit) and wrangles them into the appropriate data type if needed. Adds a new column AllFailuresOutOfSteps
WrangleData <- function(givenData) {
  
  #Wrangle all of the data into their proper types in case they were imported in a weird format.
  givenData$RunNumber <- suppressWarnings(as.numeric(givenData$RunNumber)) 
  givenData$Succeeded. <- suppressWarnings(as.logical(givenData$Succeeded.))
  givenData$Generalized. <- suppressWarnings(as.logical(givenData$Generalized.))
  givenData$StepLimit <- suppressWarnings(as.numeric(givenData$StepLimit))
  givenData$TotalError <- suppressWarnings(as.numeric(givenData$TotalError))
  givenData$NumFailedCases <- suppressWarnings(as.numeric(givenData$NumFailedCases))
  givenData$FailedByStepLimit <- suppressWarnings(as.numeric(givenData$FailedByStepLimit))
  
  #Add a new column, a boolean that says whether all of the failed cases came from running out of steps.
  givenData$AllFailuresOutOfSteps = (givenData$NumFailedCases == givenData$FailedByStepLimit)

  #Return the wrangled dataset
  return(givenData)
}




#This function takes a dataset and a step limit and returns a graph of every run that generalized at the given step limit.
GraphOriginalGeneralizations <- function(givenData, originalStep) {

  #Filter the runs to only the ones that generalized that the given step limit. Get a vector of only the run numbers.
  runsThatGeneralized <- subset(givenData, (givenData$StepLimit == originalStep & givenData$TotalError == 0))$RunNumber
  
  #Filter from the original dataset to only grab the ones that generalized at the given step limit
  fullGenData <- givenData %>%
  filter(RunNumber %in% runsThatGeneralized)
  
  #Create the graph, organized and colored by run number
  graph <- ggplot(fullGenData, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE) + ggtitle(paste("Runs that generalized at step-limit", originalStep, sep=" "))
  
  #Return the graph
  return(graph)
}




#This function takes the dataset and the step limit the problem was originally run on and returns a graph of every run that generalizes not at the given step limit.
GraphOtherGeneralizations <- function(givenData, originalStep) {
  
  #Grab all of the runs that generalized at some point
  allGeneralizations <- givenData %>%
  group_by(RunNumber) %>%
  filter(min(NumFailedCases) == 0)
  
  #Filter the runs to only the ones that generalized anywhere thats not the original step limit given and grab the run number
  generalizedElsewhere <- subset(allGeneralizations, (StepLimit == originalStep & TotalError > 0))$RunNumber
  print(paste("The number of runs that generalized with step limit !=", originalStep, "was", length(generalizedElsewhere), sep=" "))
  
  #Filter from the original dataset to only grab the ones that generalized somewhere other than the given step limit
  fullRuns <- givenData %>%
  filter(RunNumber %in% generalizedElsewhere)
  
  #Graph the runs, colored by their group number.
  graph <- ggplot(fullRuns, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)  + ggtitle(paste("Runs that generalized somewhere not step-limit", originalStep, sep=" "))
  
  return(graph)
}

#This function takes a dataset and a number which corresponds to the last step limit of the dataset. This function returns a graph containing every run that was still running out of steps when the last step limit was computed.
GraphRunningOutOfSteps <- function(givenData) {
  
  #Get the highest step limit
  lastStepLimit <- max(givenData$StepLimit)
  
  #Take the maximum number of failed cases throughout the entire dataset (hoping one of them is close to the number of total cases) and multiply it by an arbitrary number so we can filter runs and make graphs cleaner
  failedCasesThreshold <- max(givenData$NumFailedCases) * 0.05
  
  #Gets all runs that are below the given threshold and didn't generalize (min != 0)
  fewFailedCases <- givenData %>%
  group_by(RunNumber) %>%
  filter(min(NumFailedCases) < failedCasesThreshold & min(NumFailedCases) != 0)
  
  #Gets the run number from the above dataset
  outOfSteps <- subset(fewFailedCases, (StepLimit == lastStepLimit) & AllFailuresOutOfSteps)$RunNumber
  
  #get the runs that ran out of steps at the max step limit
  getRuns <- givenData %>%
  filter(RunNumber %in% outOfSteps)
  
  graph <- ggplot(getRuns, aes(x=StepLimit, y=NumFailedCases, group=factor(RunNumber), color=factor(RunNumber))) + geom_line(alpha=0.5, show.legend=FALSE)  + ggtitle(paste("Runs that are running out of steps at", lastStepLimit, sep=" "))
  
  return(graph)
}
```

```{r}
generate_GPTP_graph <- function(problem_name, datafile_200, datafile_800, inset_bounds_200, inset_bounds_800, two_color) {
  data200 <- read.csv(datafile_200, sep="")
  data800 <- read.csv(datafile_800, sep="")
  
  data200$Start = 200
  data200$xmin = inset_bounds_200[[1]]
  data200$xmax = inset_bounds_200[[2]]
  data200$ymin = inset_bounds_200[[3]]
  data200$ymax = inset_bounds_200[[4]]
  
  data800$Start = 800
  data800$xmin = inset_bounds_800[[1]]
  data800$xmax = inset_bounds_800[[2]]
  data800$ymin = inset_bounds_800[[3]]
  data800$ymax = inset_bounds_800[[4]]
  
  data200 <- data200 %>% group_by(RunNumber) %>% filter(min(NumFailedCases) == 0)
  
  runs200ThatGeneralizedAtStep200 <- subset(data200, (data200$StepLimit == 200 & data200$TotalError == 0))$RunNumber
  
  #Filter from the original dataset to only grab the ones that generalized at the given step limit
  fullGenData200 <- data200 %>%
    filter(RunNumber %in% runs200ThatGeneralizedAtStep200)
  
  if(nrow(fullGenData200) != 0) {
    fullGenData200$whereGen <- 'Original Step Limit'
  }
  
  allGeneralizations200 <- data200 %>%
    group_by(RunNumber) %>%
    filter(min(NumFailedCases) == 0)
  
  #Filter the runs to only the ones that generalized anywhere thats not the original step limit given and grab the run number
  generalizedElsewhere200 <- subset(allGeneralizations200, (StepLimit == 200 & TotalError > 0))$RunNumber
  
  #Filter from the original dataset to only grab the ones that generalized somewhere other than the given step limit
  dataGenElsewhere200 <- data200 %>%
    filter(RunNumber %in% generalizedElsewhere200)
  
  if(nrow(dataGenElsewhere200 != 0)) {
    dataGenElsewhere200$whereGen <- 'Other Step Limit'
  }

  data800 <- data800 %>% group_by(RunNumber) %>% filter(min(NumFailedCases) == 0)
  
  runs800ThatGeneralizedAtStep800 <- subset(data800, (data800$StepLimit == 800 & data800$TotalError == 0))$RunNumber
  
  #Filter from the original dataset to only grab the ones that generalized at the given step limit
  fullGenData800 <- data800 %>%
    filter(RunNumber %in% runs800ThatGeneralizedAtStep800)
  
  if(nrow(fullGenData800) != 0) {
    fullGenData800$whereGen <- 'Original Step Limit'
  }

  allGeneralizations800 <- data800 %>%
    group_by(RunNumber) %>%
    filter(min(NumFailedCases) == 0)
  
  #Filter the runs to only the ones that generalized anywhere thats not the original step limit given and grab the run number
  generalizedElsewhere800 <- subset(allGeneralizations800, (StepLimit == 800 & TotalError > 0))$RunNumber
  
  #Filter from the original dataset to only grab the ones that generalized somewhere other than the given step limit
  dataGenElsewhere800 <- data800 %>%
    filter(RunNumber %in% generalizedElsewhere800)
  
  if(nrow(dataGenElsewhere800 != 0)) {
    dataGenElsewhere800$whereGen <- 'Other Step Limit'
  }
  
  # dataTot <- rbind(data200, data800)
  
  dataTot <- rbind(fullGenData200, dataGenElsewhere200, fullGenData800, dataGenElsewhere800)
  
  # coloring <- ifelse(two_color, factor(dataTot$whereGen), factor(dataTot$RunNumber))
  
  if (two_color) {
    base <- ggplot(data=dataTot, 
                aes(x=StepLimit,y=NumFailedCases, group=interaction(Start, RunNumber), color=factor(whereGen))) + 
    geom_line(alpha=0.4) + 
    theme_bw() +
    labs(title ="",  x = "Step Limit", y = "NumFailedCases") + 
    scale_color_manual(values = c("#00BFC4", "dark red")) +
    theme(legend.position = "bottom", legend.title = element_blank())

    if (problem_name == "Fuel Cost") {
      base <- base + theme(legend.position = "none")
    }
  } else {
    base <- ggplot(data=dataTot, 
                aes(x=StepLimit,y=NumFailedCases, group=interaction(Start, RunNumber), color=factor(dataTot$RunNumber))) + 
    geom_line(alpha=0.4) + 
    theme_bw() +
    labs(title ="",  x = "Step Limit", y = "NumFailedCases") +
    theme(legend.position = "none")
  }

  facet_names <- c(
    `200` = paste(problem_name, "step limit 200 runs that generalized somewhere"),
    `800` = paste(problem_name, "step limit 800 runs that generalized somewhere")
  )
  
  lims <- list(
    list(c(inset_bounds_200[[1]], inset_bounds_200[[2]]),
         c(inset_bounds_200[[3]], inset_bounds_200[[4]])),
    list(c(inset_bounds_800[[1]], inset_bounds_800[[2]]),
         c(inset_bounds_800[[3]], inset_bounds_800[[4]]))
  )
  
  output_file = paste(problem_name, "_facet.pdf", sep = "")
  
  main <- base + facet_wrap(~ Start, ncol = 2 , labeller = as_labeller(facet_names))
 
  nStart <- length(unique(dataTot$Start))
 
  insets <- lapply(seq_len(nStart), function(i) {
    base + ggforce::facet_wrap_paginate(~ Start, nrow = 1, ncol = 1, page = i) +
    coord_cartesian(xlim = lims[[i]][[1]], ylim = lims[[i]][[2]]) +
    guides(colour = "none", x = "none", y = "none") +
    theme(strip.background = element_blank(),
           strip.text = element_blank(),
           axis.title = element_blank(),
           plot.background = element_blank())
  })
  
  insets <- tibble(x = rep(.95, nStart),
                   y = rep(1, nStart),
                   plot = insets,
                   Start = unique(dataTot$Start))
  
  finalPlot <- main +
     geom_plot_npc(data = insets,
                   aes(npcx = x, npcy = y, label = plot,
                       vp.width = 0.5, vp.height = 0.5)) +
    geom_rect(mapping = aes(x = NULL,y = NULL, xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), 
              data = dataTot,
              linetype = "dotted", 
              fill = NA, 
              colour = "black")
  
  height = 4
  if (problem_name == "LIOZ") {
    height = 4.5
  }
  ggexport(finalPlot, filename=output_file, pointsize = 1, width = 8, height=height)
}

generate_GPTP_graph("Fuel Cost", "fuelTwoRange.txt", "fuelEightRange.txt", c(30,110,800,1400), c(70,300,800,1400), TRUE)

generate_GPTP_graph("GCD", "gcdTwoRange_v2.txt", "gcdEightRange_v2.txt", c(180,370,0,30), c(750, 900, 0, 50), FALSE)

generate_GPTP_graph("LIOZ", "LIOZTwoRange_v2.txt", "LIOZEightRange_v2.txt", c(150, 300, 0, 15), c(650,900,0,15), TRUE)

generate_GPTP_graph("MC", "MCTwoRange_v2.txt", "MCEightRange_v2.txt", c(370,430,0,30), c(750,900,0,30), FALSE)
```

```{r}

mc200 <- read.csv("MCTwoRange.txt", sep="")

mc800 <- read.csv("MCEightRange_v2.txt", sep="")

# c(375, 475, 0, 50)

mc200$Start <- 200
mc200$xmin <- 375
mc200$xmax <- 475
mc200$ymin <- 0
mc200$ymax <- 50

mc800$Start <- 800
mc800$xmin <- 650
mc800$xmax <- 750
mc800$ymin <- 0
mc800$ymax <- 50

mc200 <- mc200 %>% group_by(RunNumber) %>% filter(min(NumFailedCases) == 0)

mc800 <- mc800 %>% group_by(RunNumber) %>% filter(min(NumFailedCases) == 0)

mcTot <- rbind(mc200, mc800)

base <- ggplot(data=mcTot, 
                aes(x=StepLimit,y=NumFailedCases, group=interaction(Start, RunNumber), color=factor(RunNumber))) + 
  geom_line(alpha=0.5) + 
  theme_bw() +
  labs(title ="",  x = "Step Limit", y = "NumFailedCases") +
  theme(legend.position = "none")

facet_names <- c(
  `200` = "Both MC step limit 200 runs that generalized somewhere",
  `800` = "All 8 MC step limit 800 runs that generalized somewhere"
)

# # New facet label names for dose variable
# dose.labs <- c("D0.5", "D1", "D2")
# names(dose.labs) <- c("0.5", "1", "2")
# 
# # New facet label names for supp variable
# supp.labs <- c("Orange Juice", "Vitamin C")
# names(supp.labs) <- c("OJ", "VC")
# 
# # Create the plot
# p + facet_grid(
#   dose ~ supp, 
#   labeller = labeller(dose = dose.labs, supp = supp.labs)
#   )

lims <- list(
  list(c(375, 475), c(0, 50)),
  list(c(650, 750), c(0, 50))
)

main <- base + facet_wrap(~ Start, ncol = 2 , labeller = as_labeller(facet_names))
 
nStart <- length(unique(mcTot$Start))
 
insets <- lapply(seq_len(nStart), function(i) {
   base + ggforce::facet_wrap_paginate(~ Start, nrow = 1, ncol = 1, page = i) +
     # coord_cartesian(xlim = c(650,750), ylim = c(0, 50)) +
     coord_cartesian(xlim = lims[[i]][[1]], ylim = lims[[i]][[2]]) +
     guides(colour = "none", x = "none", y = "none") +
     theme(strip.background = element_blank(),
           strip.text = element_blank(),
           axis.title = element_blank(),
           plot.background = element_blank())
 })
 
# ins1 <- base + ggforce::facet_wrap_paginate(~ Start, nrow = 1, ncol = 1, page=1) +
#     coord_cartesian(xlim = c(100,800), ylim = c(500, 550)) +
#     guides(colour = "none", x = "none", y = "none") +
#     theme(strip.background = element_blank(),
#           strip.text = element_blank(),
#           axis.title = element_blank(),
#         plot.background = element_blank())
 
# ins2 <- base + ggforce::facet_wrap_paginate(~ Start, nrow = 1, ncol = 2, page=1) +
#     coord_cartesian(xlim = c(300,500), ylim = c(500, 550)) +
#     guides(colour = "none", x = "none", y = "none") +
#     theme(strip.background = element_blank(),
#           strip.text = element_blank(),
#           axis.title = element_blank(),
#           plot.background = element_blank())
 
 
insets <- tibble(x = rep(.95, nStart),
                 y = rep(1, nStart),
                 plot = insets,
                 Start = unique(mcTot$Start))

finalPlot <- main +
   geom_plot_npc(data = insets,
                 aes(npcx = x, npcy = y, label = plot,
                     vp.width = 0.5, vp.height = 0.5)) +
  geom_rect(mapping = aes(x = NULL,y = NULL, xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), 
            data = mcTot,
            linetype = "dotted", 
            fill = NA, 
            colour = "black")

finalPlot
 
ggexport(finalPlot, filename="mcFacet.pdf", pointsize = 1, width = 8, height=3)
```